export default [{
  'id': '0',
  'title': '文章1',
  'link': '#',
  'time': new Date('2017-12-15T09:08:01.418Z'),
  'username': 'name1',
  'reason': 'reason1',
  'score': 3,
  'status': 2,
  'isExcellent': true
}, {
  'id': '1',
  'title': '文章2',
  'link': '#',
  'username': 'name2',
  'reason': 'reason2',
  'score': 0,
  'status': 0,
  'isExcellent': false
}, {
  'id': '2',
  'title': '文章3',
  'link': '#',
  'username': 'name3',
  'reason': 'reason3',
  'score': 0,
  'status': 1,
  'isExcellent': false
}, {
  'id': '3',
  'title': '文章4',
  'link': '#',
  'username': 'name4',
  'reason': 'reason4',
  'score': 0,
  'status': 1,
  'isExcellent': false
}, {
  'id': '4',
  'title': '文章5',
  'link': '#',
  'username': 'name5',
  'reason': 'reason5',
  'score': 0,
  'status': 0,
  'isExcellent': false
}]
